version: '3.8'

services:
  app:
    container_name: 'qi-jira-snow'
    image: ${image}
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ../
    env_file:
      - ./.env
    ports:
      - "8080:80"
