apiVersion: v2
name: pagopa-qi-jira-snow
description: Microservice to store JIRA SERVICE NOW
type: application
version: 0.86.0
appVersion: 0.11.35
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
    alias: pagopa-qi-jira-snow